version: "3.9"

services:
  backend:
    build: .
    command: npm run dev
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      ENVIRONMENT: 'dev'
      DATABASE_URL: 'mysql://root:@db:3306/predios'
      ACCESS_TOKEN_SECRET: '8ab580b795ed798bbc1caf1e614ebc181932ece176bc0d5aa3a45bab371ad49c'
      REFRESH_TOKEN_SECRET: '25de153e48bacc2cba9214d591f7ada9536277f91b67b28197abddcd9d56dae0'
    links:
      - db
  db:
    image: mariadb:10.4
    restart: always
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
