version: "3.9"

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      ENVIRONMENT: "dev"
      DATABASE_URL: "mysql://root:@db:3306/predios?charset=utfmb4"
      ACCESS_TOKEN_SECRET: "8ab580b795ed798bbc1caf1e614ebc181932ece176bc0d5aa3a45bab371ad49c"
      REFRESH_TOKEN_SECRET: "25de153e48bacc2cba9214d591f7ada9536277f91b67b28197abddcd9d56dae0"
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb:10.4
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # volumes:
    # - ./mysql-data:/var/lib/mysql
