version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      ENVIRONMENT: "dev"
      DATABASE_URL: "mysql://root:@db:3307/predios"
      ACCESS_TOKEN_SECRET: "8ab580b795ed798bbc1caf1e614ebc181932ece176bc0d5aa3a45bab371ad49c"
      REFRESH_TOKEN_SECRET: "25de153e48bacc2cba9214d591f7ada9536277f91b67b28197abddcd9d56dae0"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.2
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
